### PR TITLE
fix quickstart link

### PR DESCRIPTION
**Pull request by ryun**

### CODE REVIEW

**Comment by fideloper** [comment]
Hi! I think  caught this and fixed it before I saw your PR ! (You must have been looking at just the right moment).

Appreciate it in any case!

**Comment by ryun** [comment]
Ok cool, maybe I'm just crazy or something or don't understand how your using the docs, when I just clicked the link from the repo I get a 404.
https://github.com/vagrant-ops/vagrantops/blob/master/quickstart

**Comment by fideloper** [comment]
Ahhhh that makes sense!!

Sorry - those docs are an integration with readthedocs.org - specifically
vagrantops.readthedocs.org.

I'll make a note of that in description and repo readme!

Sorry I didn't realize how you meant that!

**Comment by ryun** [comment]
Right on! Nice job by the way!

**Pull request closed without merging**
